
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanjangBalok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LebarBalok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TinggiBalok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        VolumeBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        SisiKubus = new javax.swing.JTextField();
        VolumeKubus = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        VolumeBola = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        JariJari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Program Penhitung Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 310, 30);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setLayout(null);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 20, 30, 40);
        jPanel1.add(PanjangBalok);
        PanjangBalok.setBounds(170, 20, 150, 40);

        jLabel3.setText("Panjang                      :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(44, 20, 120, 40);

        jLabel4.setText("Lebar                           :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 70, 120, 40);
        jPanel1.add(LebarBalok);
        LebarBalok.setBounds(170, 70, 150, 40);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 70, 34, 40);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 120, 34, 40);
        jPanel1.add(TinggiBalok);
        TinggiBalok.setBounds(170, 120, 150, 40);

        jLabel2.setText("Tinggi                           :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 120, 120, 40);

        VolumeBalok.setText("Volume");
        VolumeBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeBalokActionPerformed(evt);
            }
        });
        jPanel1.add(VolumeBalok);
        VolumeBalok.setBounds(160, 180, 90, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel10.setText("cm");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(170, 50, 34, 40);
        jPanel2.add(SisiKubus);
        SisiKubus.setBounds(10, 50, 150, 40);

        VolumeKubus.setText("Volume");
        VolumeKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeKubusActionPerformed(evt);
            }
        });
        jPanel2.add(VolumeKubus);
        VolumeKubus.setBounds(30, 110, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Masukan Panjang Sisi");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 10, 160, 40);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        VolumeBola.setText("Volume");
        VolumeBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeBolaActionPerformed(evt);
            }
        });
        jPanel3.add(VolumeBola);
        VolumeBola.setBounds(30, 110, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Masukan Panjang Jari - Jari");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 10, 190, 40);
        jPanel3.add(JariJari);
        JariJari.setBounds(10, 50, 150, 40);

        jLabel9.setText("cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(170, 50, 34, 40);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 40, 400, 260);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void VolumeBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeBalokActionPerformed
        // TODO add your handling code here:
        int panjang,lebar,tinggi;
        panjang = Integer.parseInt(PanjangBalok.getText());
        lebar = Integer.parseInt(LebarBalok.getText());
        tinggi = Integer.parseInt(TinggiBalok.getText());
        int hasil = panjang * lebar * tinggi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil+" cm3","Hasil",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumeBalokActionPerformed

    private void VolumeKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(SisiKubus.getText());
        int hasil = sisi * sisi * sisi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah : "+hasil+" cm3","Hasil",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumeKubusActionPerformed

    private void VolumeBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(JariJari.getText());
        float hasil =(float)( (4/3) * (22/7) * (jari * jari * jari));
        try {
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah : "+hasil+" cm3","Hasil",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumeBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JariJari;
    private javax.swing.JTextField LebarBalok;
    private javax.swing.JTextField PanjangBalok;
    private javax.swing.JTextField SisiKubus;
    private javax.swing.JTextField TinggiBalok;
    private javax.swing.JButton VolumeBalok;
    private javax.swing.JButton VolumeBola;
    private javax.swing.JButton VolumeKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
